spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-secret: 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
            client-id: 528140661498-j21vs9lfflikqv66gil89b9up8ccrq7v.apps.googleusercontent.com
            scope: profile,email