spring:
  profiles:
    include: oauth
  datasource:
    url: jdbc:h2:./springsecuritylogin
    username: sa
    password: '004637'
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging.level:
  org.hibernate.SQL: debug