spring:
  datasource:
    url: jdbc:h2:./springsequritylogin
    username: sa
    password: '004637'
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging.level:
  org.hibernate.SQL: debug